#!/bin/bash

case "$1" in
  --stdout)
    echo 1 2 3
    echo 1 2 3
    echo "https://gitlab.hellyeah.com/mx/proj/merge_requests/new?utf8=%E2%9C%93&merge_request%5Bsource_project_id%5D=961&merge_request%5Bsource_branch%5D=go-update-it%2F5TfybkSHcMiWESFt4oYoQx2Okct5F0Fv&merge_request%5Btarget_project_id%5D=961&merge_request%5Btarget_branch%5D=master"
    echo 1 2 3
    echo 1 2 3
    ;;

  --stderr)
    echo 1 2 3
    echo 1 2 3
    (>&2 echo "https://gitlab.hellyeah.com/mx/proj/merge_requests/new?utf8=%E2%9C%93&merge_request%5Bsource_project_id%5D=961&merge_request%5Bsource_branch%5D=go-update-it%2F5TfybkSHcMiWESFt4oYoQx2Okct5F0Fv&merge_request%5Btarget_project_id%5D=961&merge_request%5Btarget_branch%5D=master")
    echo 1 2 3
    echo 1 2 3
    ;;

  *)
    echo running tests...
    set -euo pipefail
    export PATH="$(pwd):$PATH"
    click_test --stdout | click &> /dev/null
    click_test --stderr 2>&1 | click &> /dev/null
    click click_test --stdout &> /dev/null
    click click_test --stderr &> /dev/null
    echo done
    ;;
esac
